[tool.poetry]
name = "jb-legal-library"
version = "0.1.0"
description = ""
authors = ["OpenNyAI Team <opennyai@googlegroups.com>"]
readme = "README.md"
packages = [{include = "jugalbandi/legal_library"}]

[tool.poetry.dependencies]
python = ">=3.10, <4.0.0"
pydantic = "^1.10.9"
jb-library = {path = "../jb-library", develop = true}
jb-storage = {path = "../jb-storage", develop = true}
aiofiles = "^23.1.0"
types-aiofiles = "^23.1.0.4"
scikit-learn = "^1.2.2"
openai = "^0.27.8"
roman = "^4.1"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
mypy = "^1.3.0"
flake8 = "^6.0.0"
poethepoet = "^0.20.0"
pytest = "^7.3.1"
pytest-asyncio = "^0.21.0"
faker = "^18.10.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poe.tasks.lint]
shell = """
black jugalbandi tests
flake8 jugalbandi tests
mypy jugalbandi tests
"""
interpreter = "bash"
help = "format, lint, typecheck"


[tool.poe.tasks.test]
cmd = "python -m pytest -vv -o log_cli=1 -o log_cli_level=INFO -W 'ignore::DeprecationWarning' $FILE"
args = [{name="FILE", default="tests", positional=true}]
help = "run tests using pytest"
